### ISSUE TITLE
Remove the first column from eic_info.py

### ISSUE THREAD

**Issue by john-science** [mmb-carb/ESTA#14]
The eic_info.py file has a single dictionary with EICs as keys, and three columns of data as values. The question is: do we still need that first column? e.g.

    71073411000000: (0, 'vmt', 1.0),     # ('LDA', 'CAT', 'RUNEX')

That first column `0` is a relic of the DTIM link files. However, now it is tied into the CALVAD_VEHICLE types in some strange way.  But that is all certainly unnecessary and complicated.  So it needs to be removed.

**Comment by john-science** [comment]
The more I look at this, the more it needs to be fixed. A long time ago, when this was a DTIM clone model, it was fine to have everything tied to the 26 DTIM vehicle categories. But now having so many things tie back to these 26 arbitrary vehicle categorizations is confusing.

**Comment by leoand23** [comment]
I agree. There is no real reason for keeping that at this point. Hopefully
not too bad of an update
