### ISSUE TITLE
Add Optional DPM to NetCDF files

### ISSUE THREAD

**Issue by john-science** [mmb-carb/ESTA#15]
Users may want DPM in their NetCDF files for toxics studies.

**Comment by mdisuanco** [comment]
Stage 1 update complete: PM10/PM2.5 EMFAC totals read from csv files, speciated 1:1 (like CO), and written as a model species to NetCDF. PM10/PM2.5 are treated as separate pollutant groups and are independent of PM (PM and PM species will still be processed independent of PM10/PM2.5).

**Comment by john-science** [comment]
I think your code changes include the word "toxics". But maybe they shouldn't.

I *hope* ESTA can already process toxics, because that would just be a normal ESTA run with different speciation.  But we should check that works.

If so, probably your code should use a term more like "DPM" than "toxics".

**Comment by mdisuanco** [comment]
Yes, you're right. I'll update the code changes and notes I made to reflect it as a DPM option, not toxics.

**Comment by mdisuanco** [comment]
DPM/DPM10/DPM2.5 added to text outputs as well as netCDFs. "toxics" option now identified as "dpm" option in config files. See "20170918" version (and later) of ESTA packages for this functionality.
