### ISSUE TITLE
Can ESTA process toxics?

### ISSUE THREAD

**Issue by john-science** [mmb-carb/ESTA#17]
I believe ESTA should already be able to process toxics.  You just need to provide it different GSPRO/GSREF files.  BUT, is that the case?

We should try it and find out!

**Comment by leoand23** [comment]
Is this ticket/question still relevant since we already have an ESTA version that process Toxics? has anyone tried it yet?

**Comment by john-science** [comment]
If ESTA is already production Toxics, you can safely close this ticket.
