### ISSUE TITLE
Output file name

### ISSUE THREAD

**Issue by leoand23** [mmb-carb/ESTA#3]
It would be nice to add user functionality for the output file name to add the speciation profile used when creating netCDF output?.
For example, the current default name is:

st_4k.mv.v0220..2013.2013365..e14..ncf.gz
If we used 2013 speciation gsref with vintage 11jan17, it would be nice to be able to keep track of this in the file name to have :

st_4k.mv.v0220..2013.2013365..e14.**gsref_13_11jan17**.ncf.gz

**Comment by john-science** [comment]
I will also look into putting this speciation information in the NetCDF header notes.

**Comment by john-science** [comment]
Is it enough to have the speciation information in the NetCDF header, or do we still want it in the file name?  After considering it, I think the best way to add it to the file name would be to add an optional argument to the config file. Something like:

    [Output]
    speciation_version: saprc07_20170915

This has the benefit of being easy to use and optional, but it would be one more thing that user would have to know about to config correctly.

**Comment by leoand23** [comment]
I like your the idea of configurable via config file. This way the option
is available for the user.


On Sep 15, 2017 12:42 PM, "John Stilley" <notifications@github.com> wrote:

Is it enough to have the speciation information in the NetCDF header, or do
we still want it in the file name? After considering it, I think the best
way to add it to the file name would be to add an optional argument to the
config file. Something like:

[Output]
speciation_version: saprc07_20170915

This has the benefit of being easy to use and optional, but it would be one
more thing that user would have to know about to config correctly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mmb-carb/ESTA/issues/3#issuecomment-329880762>, or mute
the thread
