### ISSUE TITLE
More varied grid examples?

### ISSUE THREAD

**Issue by john-science** [mmb-carb/ESTA#8]
Would it be nicer if we had full examples of ESTA run on different grids?  Perhaps a SCAQMD and BAAQMD example, with their own surrogates?

**Comment by leoand23** [comment]
It might be useful. You would have to create the spatial surrogates on the different grid as well as the GRIDCRO2D for that particular domain which might take some time.

**Comment by theJollySin** [comment]
The spatial surrogates for the 4km SCAQMD and BAAQMD would mean shifting the I and J values in the surrogates (and cropping the grid).  That would be fast.

I wonder if someone (like maybe the districts or our modeling group) already have the GRIDCRO2D files somewhere.

**Comment by john-science** [comment]
Since we have removed the GRIDCRO2D files, this ticket is already done.
